### ISSUE TITLE
Author resources endpoint shows only one resource

### ISSUE THREAD

**Issue by games647** [SpiGetOrg/Spiget#1]
I'm accessing: https://api.spiget.org/v1/authors/games647/resources and it shows only FastLogin, but I have 7 projects hosted on Spigot. Example ChangeSkin which is already tracked by your website and seems to match to the same id:

https://api.spiget.org/v1/resources/21469

But still it display only one entry.

**Comment by InventivetalentDev** [comment]
That's weird, your [author-info](http://api.spiget.org/v1/authors/games647) also shows only 1 ID, so there was an issue with properly updating the data. 
As I'm currently working on /v2, I _probably_ won't fix this for /v1.  

Version 2 seems to work fine, so I suggest you use that for now. (https://api.spiget.org/v2/authors/games647/resources)

**Comment by games647** [comment]
Thank you. I didn't know about v2.
