### ISSUE TITLE
Slim Application Error returned when checking versions/latest on premium resources

### ISSUE THREAD

**Issue by GamerKing195** [SpiGetOrg/Spiget#11]
![screenshot 2017-12-26 at 12 56 23 am](https://user-images.githubusercontent.com/13630061/34372800-63e905e0-ea94-11e7-8764-e98e10ceb157.png)

This error is returned after pinging any premium resource at /versions/latest.
Example of a URL that is broken found [here](https://api.spiget.org/v2/resources/49313/versions/latest).

**Comment by InventivetalentDev** [comment]
Unfortunately, Spiget currently doesn't properly support premium resource versions.
This has been one of my TODOs for quite a while, but I'll try to find a solution soon :)

**Comment by InventivetalentDev** [comment]
Alright, I added some stuff to hopefully fix this in these commits:
https://github.com/SpiGetOrg/SpigetParser/commit/576d8b94334c809acc117f8b0cb20a708ca827a6
https://github.com/SpiGetOrg/SpigetFetcher/commit/864f8e90e9db8d64dc1c235d776226e290cd7ae7
https://github.com/SpiGetOrg/RestAPI/commit/e12b7512cf2e5281cda66d24b3c8ee77c8dc387e

Next time you update your resource, you should be able to properly get the latest version :)
