### ISSUE TITLE
Slim application error while getting latest version of free resource

### ISSUE THREAD

**Issue by GamerKing195** [SpiGetOrg/Spiget#12]
When retrieving the latest version of my free resource on spigot via this URL https://api.spiget.org/v2/resources/24610/updates/latest it returns a slim application error.

Edit: this also occurs with premium resources, EX https://api.spiget.org/v2/resources/49313/updates/latest

**Comment by GamerKing195** [comment]
Update, the issue with free resources either fails like the example or contains an outdated version, EX: 

Spigot link: https://api.spiget.org/v2/resources/39719/versions/latest 
                   https://www.spigotmc.org/resources/autoupdaterapi.39719/

Example with premium resource: https://www.spigotmc.org/resources/up2date.49313/
                                                        https://api.spiget.org/v2/resources/49313/versions/latest 

As a note this issue is having significant effects on my plugins as it is a part of the main functionality for two of them, it would be greatly appreciated if this could be fixed asap.

**Comment by InventivetalentDev** [comment]
Currently working on a way to fix this. Should hopefully be done in a few days c:

**Comment by GamerKing195** [comment]
Hey there, any updates on the fix?

**Comment by InventivetalentDev** [comment]
This should be fixed internally now, but you'll have to post an update for your resource in order for Spiget to show the latest version.

**Comment by GamerKing195** [comment]
Ok cool, thanks!
