### ISSUE TITLE
Webhook registration: Connection failed. Status code: -1

### ISSUE THREAD

**Issue by Th3Shadowbroker** [SpiGetOrg/Spiget#22]
I've tried to register a new webhook via the registration form on https://spiget.org/webhook/.
Here's a screenshot of the error message I got:
![screenshot](http://sc.m4taiori.de/211026.png)

**Comment by InventivetalentDev** [comment]
You should be able to click on the `click here` thingy at the bottom if the url you specified is reachable. The error is actually talking about the connection to that url, but I guess the message is a bit misleading.

**Comment by Th3Shadowbroker** [comment]
Oh okay. I were just a bit irritated because it sounds like something went wrong on API-Side.
Sorry 😅
