### ISSUE TITLE
Resource 6239 not found

### ISSUE THREAD

**Issue by PyvesB** [SpiGetOrg/Spiget#28]
Hello! 👋🏻 

When I try to hit endpoint https://api.spiget.org/v2/resources/6239 to retrieve information about the [Advanced Achievements](https://www.spigotmc.org/resources/advanced-achievements.6239/) resource, I get an error:
```
{
  "error": "resource not found"
}
```

The same API call worked fine for many months, it only seems to have broken recently.

Thanks in advance for your help!

**Comment by InventivetalentDev** [comment]
Requested a manual update for that resource & it should show up again in a few hours. Not really sure why it disappeared.

**Comment by PyvesB** [comment]
Thank you! I'll probably be able to close both this issue and the linked PR in a few hours then. :)

**Comment by PyvesB** [comment]
The problematic resource was recently deleted from Spigot, so this particular example is no longer a problem. I've not spotted any issues with other API responses, so I'll go ahead and close this.
