### ISSUE TITLE
resource .jar files from Spiget and SpigotMC are not the same files

### ISSUE THREAD

**Issue by alvesvaren** [SpiGetOrg/Spiget#30]
When comparing the downloaded files from spiget and spigot, the files differ both in size, checksum and content. Is there any reason for this and if so why?

**Comment by InventivetalentDev** [comment]
https://discordapp.com/channels/398243219961413653/482177092889346059/763081182132699137

**Comment by alvesvaren** [comment]
Which server?

**Comment by InventivetalentDev** [comment]
`resource downloads from spiget are cached and are quite unreliable at this point due to spigotmcs cloudflare protection. I would recommend downloading stuff directly` 
https://yeleha.co/discord

**Comment by alvesvaren** [comment]
Oh ok. Thanks!
