### ISSUE TITLE
Returns 0 for author-id in v2/search/resources/'plugin-name'

### ISSUE THREAD

**Issue by Osiris-Team** [SpiGetOrg/Spiget#32]
Url: https://api.spiget.org/v2/search/resources/Essentials
I got this issue for the second JsonObject returned(chat-essentials.871).
It not only misses the author-id, but also the category I guess.
The actual author-id for this plugin should be 21516.
Json:
```json
  {
    "file": {
      "type": ".jar",
      "size": 3.7,
      "sizeUnit": "KB",
      "url": "resources/chat-essentials.871/download?version=2974"
    },
    "contributors": "imzeevee,yoitsjimby",
    "likes": 0,
    "testedVersions": [],
    "links": {
      "discussion": "threads/chat-essentials.25958/"
    },
    "name": "Chat Essentials",
    "tag": "Clearchat selfclearchat and mute chat all in one",
    "version": {
      "id": 2974
    },
    "author": {
      "id": 0
    },
    "category": {
      "id": 0
    },
    "rating": {
      "count": 0,
      "average": 0
    },
    "releaseDate": 1407457680,
    "updateDate": 1407457680,
    "downloads": 1373,
    "icon": {
      "url": "",
      "data": ""
    },
    "existenceStatus": 1,
    "premium": false,
    "id": 871
  }
``` 

This https://api.spiget.org/v2/authors/21516/resources will return an empty JsonArray even though it should display ChatEssentials information.
This https://api.spiget.org/v2/authors/21516 kinda works fine though.

**Comment by Osiris-Team** [comment]
@InventivetalentDev Do you need more information?

**Comment by InventivetalentDev** [comment]
Requested manual updates for a bunch of resources with a `0` author, should be fixed in a couple hours

**Comment by Osiris-Team** [comment]
Any news?

**Comment by Osiris-Team** [comment]
Closing because of no response
