### ISSUE TITLE
New resources list is not being updated since months.

### ISSUE THREAD

**Issue by Osiris-Team** [SpiGetOrg/Spiget#40]
https://api.spiget.org/v2/resources/new

**Comment by InventivetalentDev** [comment]
It's paginated, there should be different ones on the later pages.  
Also you might want to check https://api.spiget.org/v2/resources/recentUpdates instead, /new returns all resources where the updateDate == releaseDate

**Comment by Osiris-Team** [comment]
Ok that makes sense, but it was different before.
