### ISSUE TITLE
cdn.spiget.org for version specific files

### ISSUE THREAD

**Issue by rampd2** [SpiGetOrg/Spiget#41]
It seems that your API returns a diffrent download server if a specific version of a resource is requested, that makes scripting it impossible because it just forwards to spigotmc.org whitch has Cloudflare protection on and returns http error `503` when using `curl`.

correct:
```bash
$ curl -I https://api.spiget.org/v2/resources/9089/download | grep location
location: https://cdn.spiget.org/file/spiget-resources/9089.zip
```
incorrect / direct download with Cloudflare protection (`503` with `curl`)
```
$ curl -I https://api.spiget.org/v2/resources/9089/versions/latest/download | grep location
location: https://spigotmc.org/resources/9089/download?version=367353
```

**Comment by InventivetalentDev** [comment]
```
Download a specific resource version

Note: This only redirects to the stored download location and might not download a file (i.e. for external resources)
```
http://spiget.org/documentation/#!/resources/get_resources_resource_versions_version_download  


the latest version (from the /download route) is cached on spiget's servers, specific versions are not

**Comment by rampd2** [comment]
But the what is the reason to use spiget in that case?
It's good because of its cache not the redirection to a already good structured address.

**Comment by InventivetalentDev** [comment]
> But the what is the reason to use spiget in that case?

It gives you the location of a specific version of that resource. Mainly a remnant of when you use to be able to somewhat bypass cloudflare for downloads.   

Downloading and storing every possible version of all ~60k resources would simply be way too much data, especially as a free-to-use project, sorry.

**Comment by itzg** [comment]
And I'm sorry, I had been misreading the cdn hostname this whole time -- I thought it was spigotmc CDN address and not yours at spiget. I'm actually surprised your site is caching as much as it is and very grateful.

**Comment by InventivetalentDev** [comment]
😄 yeah an official cdn would be awesome, probably unlikely though.

**Comment by rampd2** [comment]
> Mainly a remnant of when you use to be able to somewhat bypass cloudflare for downloads.

Ok, I didn't know spigotmc was not blocking previously, now I understand the reason for this forward.

> Downloading and storing every possible version of all ~60k resources would simply be way too much data, especially as a free-to-use project, sorry.

Nothing to be sorry about.


&nbsp;

Also very happy to be even able to use your cdn 😄

_I close this issue now, because I think none of us could really do something about it._
