### ISSUE TITLE
Issues with obtaining Resource Reviews

### ISSUE THREAD

**Issue by MrEAlderson** [SpiGetOrg/Spiget#47]
Hey,
first of all thank you for creating this wonderful project.
However, there two bugs with the the "Resource Reviews" API, which I already addressed in your Discord:
1. The "responseMessage" is never present
2. "rating.count" returns always 1. The average seems to be correct tho, if it's supposed to represent the average count given by the user.

**Comment by InventivetalentDev** [comment]
1. was an issue with the api, should be fixed soon :)

2. the count is intended to be 1 in the context of `/resources/{}/reviews` since it's only for a single review (use the number of objects in the returned array for the actual count). in `/resources/{}` it's the number of reviews.
