### ISSUE TITLE
A way to filter Webhooks for specific Resources

### ISSUE THREAD

**Issue by HappyBavarian07** [SpiGetOrg/Spiget#49]
Could you maybe make it so that we can filter the Data that is send to the Webhook. (For Example: I want to receive an Update Message for one of my Plugins on Discord, but i don’t want to make a bot that is always online.)
Spiget is such an amazing tool and i use it in 3 of my 5 Plugins for Updating automatically.

(And sorry for my bad English. It‘s not my main Language.)

**Comment by InventivetalentDev** [comment]
not doing this. it's easy enough to run the webhooks through something like https://pipedream.com/ and do the filtering yourself :)

**Comment by HappyBavarian07** [comment]
its ok thanks for the answer. now i know how to do it.
