### ISSUE TITLE
Download leads to a redirect, which leads to 503 error

### ISSUE THREAD

**Issue by miranda1000** [SpiGetOrg/Spiget#55]
I'm trying to download one of my plugins ([MineIt](https://www.spigotmc.org/resources/mineit-1-8-1-19.69161/)) with Spiget. The URL that I'm using is `https://api.spiget.org/v2/resources/69161/versions/latest/download`, and I'm calling it with `wget`.

The first call seems to give me the correct Spigot url with a redirect, but then Spigot returns error 503 (probably Cloudflare blocking me). Does Spiget "bind" the download, or just redirects it to the Spigot official page? If that's the case, there's any library that I can call from Ubuntu CLI?

Here are the logs:
```
--2022-12-17 17:39:37--  https://api.spiget.org/v2/resources/69161/versions/latest/download
Resolving api.spiget.org (api.spiget.org)... 172.67.65.206, 104.24.30.82, 104.24.31.82, ...
Connecting to api.spiget.org (api.spiget.org)|172.67.65.206|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://spigotmc.org/resources/69161/download?version=464056 [following]
--2022-12-17 17:39:37--  https://spigotmc.org/resources/69161/download?version=464056
Resolving spigotmc.org (spigotmc.org)... 104.27.196.95, 104.27.195.95, 2606:4700:21::681b:c35f, ...
Connecting to spigotmc.org (spigotmc.org)|104.27.196.95|:443... connected.
HTTP request sent, awaiting response... 503 Service Temporarily Unavailable
2022-12-17 17:39:37 ERROR 503: Service Temporarily Unavailable.
```

**Comment by InventivetalentDev** [comment]
as mentioned in the docs, the /versions download routes return a redirect - to download the cached version of the latest version, use the /download route

**Comment by miranda1000** [comment]
> to download the cached version of the latest version

What if I want to get a previous version?

**Comment by InventivetalentDev** [comment]
you can't, unfortunately. 
I mentioned a few times in other issues & on discord that caching the files for every resource version would just be way too much data. :/

depending on your use case, you might be able to request an IP whitelist from spigotmc directly.

**Comment by miranda1000** [comment]
> depending on your use case, you might be able to request an IP whitelist from spigotmc directly.

Oh, I could do that.
Thanks for your help, for now I'll just keep the "latest" version.
