### ISSUE TITLE
Handling Premium Resources | Request

### ISSUE THREAD

**Issue by DevCubeHD** [SpiGetOrg/Spiget#6]
Hey I wanted to know if I can get information from premium resources like the buyers list in any way?
Thank you very much!

**Comment by MiniDigger** [comment]
related: https://www.spigotmc.org/threads/allow-access-to-premium-plugin-sites-without-registration.201144/#post-2092954

**Comment by DevCubeHD** [comment]
Thank you! I cant understand why.. but if he is with that opinion..
