### ISSUE TITLE
Download count of resources not updating

### ISSUE THREAD

**Issue by iZefix** [SpiGetOrg/Spiget#9]
Hi,
I am trying to use your API for my Website and, unfortunatly, I am missing more than 1000 downloads for some of my resources. Is there a way to fix this? I thought the resources should get updated at least with every resource update but this is not the case. My plugin MagicWands has almost 2000 downloads but there are only about 700 shown.

Thanks a lot.

**Comment by InventivetalentDev** [comment]
Resources are only updated when the author publishes an update.  
So resources which haven't been updated for a while, won't receive any new information. The download count isn't exact.
